### ISSUE TITLE
how to use this code

### ISSUE THREAD

**Issue by nakshatra-nahar** [tihiy-production/php-image-compressor#1]
please show a demonstration of how to use this code

**Comment by tihiy-production** [comment]
@nakshatra-nahar What exactly is not clear to you from the Readme file?

**Comment by nakshatra-nahar** [comment]
i'm kind a newbie to PHP can you please tell  me step by step how to execute this file

**Comment by tihiy-production** [comment]
@nakshatra-nahar Thank you for contacting, but your comment does not apply to the problem of the library. Read the Composer documentation.
