### ISSUE TITLE
Same size.

### ISSUE THREAD

**Issue by emresaracoglu** [tihiy-production/php-image-compressor#2]
Hello,

thank you for this repo, the original photo and the compressed photo are the same sizes. Is there a bug, I wonder?

Debian 10

**Comment by tihiy-production** [comment]
1. Be sure that you installed required libraries on your OS: jpegoptim and pngquant.
2. If your image has PNG format and was already compressed then size can be the same.

@emresaracoglu fyi

**Comment by emresaracoglu** [comment]
It was installed before, but I checked it again, and it is installed.: `jpegoptim` and `pngquant`
Maybe. PNG, maybe you can have a different result, you can try. [this photo](https://send.aurorabilisim.com/download/041aede2e818bbeb/#HBjV5W6ZeieyD8PshuEP9A)
